# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoffeeApp(object):
    def setupUi(self, CoffeeApp):
        CoffeeApp.setObjectName("CoffeeApp")
        CoffeeApp.resize(400, 300)
        self.tableWidget = QtWidgets.QTableWidget(CoffeeApp)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 381, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.addButton = QtWidgets.QPushButton(CoffeeApp)
        self.addButton.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(CoffeeApp)
        QtCore.QMetaObject.connectSlotsByName(CoffeeApp)

    def retranslateUi(self, CoffeeApp):
        _translate = QtCore.QCoreApplication.translate
        self.addButton.setText(_translate("CoffeeApp", "Add"))
